//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPicking
    {
        public int Id { get; set; }
        public Nullable<int> Class { get; set; }
        public string Date { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public string Code { get; set; }
        public string StartPrice { get; set; }
        public string StartVolume { get; set; }
        public string YesterdayVolume { get; set; }
        public string Remark { get; set; }
        public string CreateDate { get; set; }
        public string AccumulatedGain { get; set; }
        public string StockPickingId { get; set; }
        public string AccumulatedDate { get; set; }
        public string CreateId { get; set; }
        public Nullable<bool> Approve { get; set; }
        public string OpeningPrice { get; set; }
        public string SuspendDate { get; set; }
    }
}
