//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockGroupTrend
    {
        public int Id { get; set; }
        public Nullable<int> StockGroupId { get; set; }
        public string Date { get; set; }
        public Nullable<bool> StrengthType { get; set; }
        public Nullable<decimal> StrengthPercent { get; set; }
        public Nullable<int> RedLight { get; set; }
        public Nullable<int> GreenLight { get; set; }
        public string UpdateTime { get; set; }
        public string Remark { get; set; }
    }
}
