//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockIndex
    {
        public int Id { get; set; }
        public string DayOfWeek { get; set; }
        public string Date { get; set; }
        public string DJI { get; set; }
        public string DJI_QuoteChange { get; set; }
        public string NASDAQ { get; set; }
        public string NASDAQ_QuoteChange { get; set; }
        public string PHLX { get; set; }
        public string PHLX_QuoteChange { get; set; }
        public string MTX { get; set; }
        public string MTX_QuoteChange { get; set; }
        public string MTX_Open { get; set; }
        public string MTX_High { get; set; }
        public string TX { get; set; }
        public string TX_QuoteChange { get; set; }
        public string TX_Open { get; set; }
        public string TX_High { get; set; }
        public string TAIEX { get; set; }
        public string TAIEX_Open { get; set; }
        public string TAIEX_High { get; set; }
        public string ContinueName { get; set; }
        public string Remark { get; set; }
        public string Trend { get; set; }
        public string DJI_QuotePercent { get; set; }
        public string NASDAQ_QuotePercent { get; set; }
        public string PHLX_QuotePercent { get; set; }
        public string MTX_QuotePercent { get; set; }
        public string TX_QuotePercent { get; set; }
        public string TAIEX_QuoteChange { get; set; }
        public string TAIEX_QuotePercent { get; set; }
        public string Financing { get; set; }
        public string Volume { get; set; }
        public string TPEx { get; set; }
        public string TPEx_QuoteChange { get; set; }
        public string TPEx_QuotePercent { get; set; }
        public string MTX_Volume { get; set; }
        public string TX_Volume { get; set; }
        public string JuridicaPerson { get; set; }
        public string USD_Index { get; set; }
        public string USD_IndexQuoteChange { get; set; }
        public string USD_IndexQuotePercent { get; set; }
        public string OIL_Index { get; set; }
        public string OIL_QuoteChange { get; set; }
        public string BTC_Index { get; set; }
        public string BTC_QuoteChange { get; set; }
        public string Gold_Index { get; set; }
        public string Gold_QuoteChange { get; set; }
        public string VHSI_Index { get; set; }
        public string VHSI_QuoteChange { get; set; }
        public string DAX_Index { get; set; }
        public string DAX_QuoteChange { get; set; }
        public string NIKKEI_Index { get; set; }
        public string NIKKEI_QuoteChange { get; set; }
        public string Ups { get; set; }
        public string Downs { get; set; }
        public string UpsHalf { get; set; }
        public string DownsHalf { get; set; }
        public string TSM_Index { get; set; }
        public string TSM_IndexQuotePercent { get; set; }
        public string NVDA_Index { get; set; }
        public string NVDA_IndexQuotePercent { get; set; }
        public string AAPL_Index { get; set; }
        public string AAPL_IndexQuotePercent { get; set; }
        public string MSFT_Index { get; set; }
        public string MSFT_IndexQuotePercent { get; set; }
        public string GOOG_Index { get; set; }
        public string GOOG_IndexQuotePercent { get; set; }
        public string FB_Index { get; set; }
        public string FB_IndexQuotePercent { get; set; }
        public string BAC_Index { get; set; }
        public string BAC_IndexQuotePercent { get; set; }
        public string MU_Index { get; set; }
        public string MU_IndexQuotePercent { get; set; }
        public string TSLA_Index { get; set; }
        public string TSLA_IndexQuotePercent { get; set; }
        public string C10YearBond_Index { get; set; }
        public string C10YearBond_IndexQuotePercent { get; set; }
        public string TX_Low { get; set; }
        public string MTX_Low { get; set; }
    }
}
