/****** SSMS 中 SelectTopNRows 命令的指令碼  ******/
SELECT TOP (1000) CAST(REPLACE (REPLACE (NASDAQ_QuotePercent, '%', ''),'+','') as decimal)as dog
      ,[DayOfWeek]
      ,[Date]
      ,[DJI]
      ,[DJI_QuoteChange]
      ,[DJI_QuotePercent]
      ,[NASDAQ]
      ,[NASDAQ_QuoteChange]
      ,[NASDAQ_QuotePercent]
      ,[PHLX]
      ,[PHLX_QuoteChange]
      ,[PHLX_QuotePercent]
      ,[MTX]
      ,[MTX_QuoteChange]
      ,[MTX_QuotePercent]
      ,[MTX_Open]
      ,[MTX_High]
      ,[MTX_Volume]
      ,[TX]
      ,[TX_QuoteChange]
      ,[TX_QuotePercent]
      ,[TX_Open]
      ,[TX_Volume]
      ,[TX_High]
      ,[TAIEX]
      ,[TAIEX_QuoteChange]
      ,[TAIEX_QuotePercent]
      ,[TAIEX_Open]
      ,[TAIEX_High]
      ,[ContinueName]
      ,[Remark]
      ,[Trend]
      ,[Financing]
      ,[Volume]
      ,[TPEx]
      ,[TPEx_QuoteChange]
      ,[TPEx_QuotePercent]
      ,[JuridicaPerson]
      ,[USD_Index]
      ,[USD_IndexQuoteChange]
      ,[USD_IndexQuotePercent]
  FROM [StockWarehouse].[dbo].[StockIndex]
  order by dog desc