/****** SSMS 中 SelectTopNRows 命令的指令碼  ******/
SELECT TOP (1000) [Id]
      ,[DayOfWeek]
      ,[Date]
      ,[DJI]
      ,[DJI_QuoteChange]
      ,[DJI_QuotePercent]
      ,[NASDAQ]
      ,[NASDAQ_QuoteChange]
      ,[NASDAQ_QuotePercent]
      ,[PHLX]
      ,[PHLX_QuoteChange]
      ,[PHLX_QuotePercent]
      ,[MTX]
      ,[MTX_QuoteChange]
      ,[MTX_QuotePercent]
      ,[MTX_Open]
      ,[MTX_High]
      ,[MTX_Volume]
      ,[TX]
      ,[TX_QuoteChange]
      ,[TX_QuotePercent]
      ,[TX_Open]
      ,[TX_Volume]
      ,[TX_High]
      ,[TAIEX]
      ,[TAIEX_QuoteChange]
      ,[TAIEX_QuotePercent]
      ,[TAIEX_Open]
      ,[TAIEX_High]
      ,[ContinueName]
      ,[Remark]
      ,[Trend]
      ,[Financing]
      ,[Volume]
      ,[TPEx]
      ,[TPEx_QuoteChange]
      ,[TPEx_QuotePercent]
      ,[JuridicaPerson]
      ,[USD_Index]
      ,[USD_IndexQuoteChange]
      ,[USD_IndexQuotePercent]
   FROM [StockWarehouse].[dbo].[StockIndex] 
 where Id='3254'


   update [StockWarehouse].[dbo].[StockIndex]  set DayOfWeek='二',TX='15690',TAIEX='15673',TPEx='206.95',DJI='33310',NAS_DAQ='12328',PHLX='2978' ,USD_Index='102.1',OIL_Index='71.42',BTC_Index='26972'
  -- OIL_Index='82.99',OIL_QuoteChange='-0.27',BTC_Index='30196',BTC_QuoteChange='+167.00'   
   where Id='4279'